# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    steps:
      - run:
          name: test
          commands:
            - echo 'no tests, just say us Okay!'
      - deploy:
          #develop:
          branch: master
          commands:
            - sh ./deploy_dev.sh

