# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/laravel_pj1
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0-apache-node-browsers
    steps:
      - checkout

      - run:
          name: test
          command: echo 'no tests, just say us Okay!'
      - deploy:
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then 
              ./deploy.sh ${CIRCLE_BRANCH};
            elif [ $CIRCLE_BRANCH == "staging" ]; then
              ./deploy.sh ${CIRCLE_BRANCH};
            elif [ $CIRCLE_BRANCH == "production" ]; then
              ./deploy.sh ${CIRCLE_BRANCH};
            fi
